React-Redux integration.
somoye123/Book-store pull request #2
Opened 2020-10-22 13:03 UTC by tzvaita

In this milestone, we: 
- Created all the requested directories.
- Implemented App, Booklist, Book, and BooksForm components.
- Defined Redux actions and reducers.
- Initialized the Redux store.

Thanks for reviewing.

Somoye and Tennyson

2020-10-22 19:11 UTC, mikenath223 requested changes
### Hi Team 👋

**Good work on this.👍**

- [ ] Kindly note comments on your code.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-10-22 19:12 UTC, mikenath223 commented
- Code still in review.

2020-10-22 19:13 UTC, mikenath223 commented on src/common/constantModule.js
> +      id: Math.floor(Math.random() * 1000),
- [ ] Consider wrapping the randomId generator as a function and calling it in each case.

2020-10-22 19:14 UTC, mikenath223 commented on src/containers/BooksForm.js
> +    <input type="text" />
- [ ] The BookForm should contain the handleChange function and call it on the form input.

2020-10-22 19:16 UTC, mikenath223 commented on src/containers/BooksForm.js
> +  <form className="bookform-section">
- [ ] The BookForm should contain the handleSubmit function and should be attached to the form elemnt.

2020-10-22 19:17 UTC, mikenath223 commented on src/containers/BooksList.js
> +  const booksList = books.map(book => <Book book={book} key={Math.random()} />);
- [ ] The BookList should contain the handle remove function and attached to each Book component.

2020-10-22 19:20 UTC, mikenath223 commented on src/common/constantModule.js
> +      id: Math.floor(Math.random() * 1000),
- [ ] Kindly wrap this randomId generator in a function and call it on each id.

2020-10-23 11:32 UTC, whiz25 approved these changes
## Approved :clap: 
All seems okay. Merge and proceed to the next milestone.

### Martin Afani

2020-10-23 12:10 UTC, merged